# Generated by Django 2.0 on 2018-02-28 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('body', models.TextField(blank=True, default=None, null=True)),
                ('insertTime', models.TimeField(blank=True, default=None, null=True)),
                ('insertDate', models.DateField(blank=True, default=None, null=True)),
                ('today', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
    ]
